spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile:
      - local
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: local

server:
  port: 5000
